import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
       <Image className={styles.img} src="/codding.jpg" width="350px" height="300px" />
       <p className={styles.p}>Welcome to Onlinewear!!</p>
      </div>
    </div>
  )
}
